---
# COPY and this file to secrets.yml and modify as needed
development:
  DB_KEY: pFrP9v4qQNRvpEeLl4RL0s8C3pmMyOKTYrjHhb2rq4g=
  DATABASE_URL: sqlite://app/db/store/development.db
  SECURE_SCHEME: HTTP

test:
  DB_KEY: vgUZYN/SwldEppmt0MFgxFFrGWqmARCcZsIvU4l/Dwc=
  DATABASE_URL: sqlite://app/db/store/test.db
  SECURE_SCHEME: HTTP

production:
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  DATABASE_URL: <set to production DB>
  SECURE_SCHEME: HTTPS
