---
# COPY and this file to secrets.yml and modify as needed
development:
  SECURE_SCHEME: HTTP
  DATABASE_URL: sqlite://app/db/store/development.db
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  DB_KEY: pFrP9v4qQNRvpEeLl4RL0s8C3pmMyOKTYrjHhb2rq4g=
  SIGNING_KEY: nNuYJVHnMTPfArqFo3Rb81xvXoPDuqcdoUhjWVfGooE=
  VERIFY_KEY: j50XXfk5tXJ9oWomovLVOFlbgKKY/YSDPHAy4s1fA6U=
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  GITHUB_ACCOUNT_URL: https://api.github.com/user

test:
  SECURE_SCHEME: HTTP
  DATABASE_URL: sqlite://app/db/store/test.db
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  DB_KEY: pFrP9v4qQNRvpEeLl4RL0s8C3pmMyOKTYrjHhb2rq4g=
  SIGNING_KEY: nNuYJVHnMTPfArqFo3Rb81xvXoPDuqcdoUhjWVfGooE=
  VERIFY_KEY: j50XXfk5tXJ9oWomovLVOFlbgKKY/YSDPHAy4s1fA6U=
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  GITHUB_ACCOUNT_URL: https://api.github.com/user

production:
  SECURE_SCHEME: HTTPS
  DATABASE_URL: <do not edit - allow production server to set>
  MSG_KEY: <`rake new_key:msg`>
  DB_KEY: <`rake new_key:db`>
  SIGNING_KEY: <`rake newkey:signing`> # needed by client app; used in api tests
  VERIFY_KEY: <`rake newkey:signing`>
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  GITHUB_ACCOUNT_URL: https://api.github.com/user
